#!/usr/bin/env node
// Regenerate the interactive launch-readiness tool (docs/launch-readiness.html)
// from the curated guides (tools/launch-readiness/guides.json) + the LIVE status
// in the register (docs/launch-readiness.md). A hook runs this whenever the
// register changes; run it by hand with:  node tools/launch-readiness/generate.mjs
//
// - Each curated item's `match` names the register ref whose ✅ status marks it
//   complete (baked). Closed items show done automatically; the user's own ticks
//   for still-open items persist in the browser.
// - Any OPEN launch-namespace ref (A#, B#, Q#, LEAD-#, GAP-#) that appears in the
//   register but isn't covered by a curated item is surfaced in a "Recently added
//   to the register" section, so a newly-appended gap is never silently missed.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(here, "..", "..");
const REGISTER = path.join(ROOT, "docs", "launch-readiness.md");
const GUIDES = path.join(here, "guides.json");
const TEMPLATE = path.join(here, "template.html");
const OUT = path.join(ROOT, "docs", "launch-readiness.html");

// Refs that are intentionally represented by a curated item under a different
// primary ref, so the auto-append safety-net shouldn't duplicate them.
const COVERED_EXTRA = ["B5", "Q12"];

const REF_RE = /^([A-Za-z]{1,6}\d[\w-]*|[A-Za-z]{2,6}-\d+)$/;
const LAUNCH_NS_RE = /^(A\d+|B\d+|Q\d+|GAP-\d+|LEAD-\d+)$/;

// ── 1. parse the register for ref → status + title ──────────────────────────
function parseRegister(md) {
  const status = {}; // ref -> "done" | "open"
  const title = {};
  for (const raw of md.split("\n")) {
    const line = raw.trim();
    if (!line.startsWith("|")) continue;
    let cells = line.split("|").map((s) => s.trim());
    if (cells[0] === "") cells.shift();
    if (cells.length && cells[cells.length - 1] === "") cells.pop();
    if (!cells.length) continue;
    const ref = cells[0].replace(/[*`]/g, "").trim();
    if (!REF_RE.test(ref)) continue; // header / separator / prose row
    // Status is the LAST cell only — a ✅ in a prose cell (e.g. "PH3-5 ✅" while
    // the row's own status is "⬜ open") must NOT mark the row done.
    const done = /✅/.test(cells[cells.length - 1]);
    if (status[ref] !== "done") status[ref] = done ? "done" : "open";
    if (cells[1]) title[ref] = cells[1].replace(/[*`]/g, "").trim();
  }
  return { status, title };
}

// ── 2. load curated guides + bake live status ───────────────────────────────
function build() {
  const md = readFileSync(REGISTER, "utf8");
  const { status, title } = parseRegister(md);
  const guides = JSON.parse(readFileSync(GUIDES, "utf8"));

  const covered = new Set(COVERED_EXTRA);
  const collectRefs = (s) => (s || "").match(/[A-Za-z]{2,6}-\d+|[A-Za-z]{1,6}\d[\w-]*/g) || [];

  let baked = 0;
  for (const sec of guides.sections) {
    for (const it of sec.items) {
      if (it.match) covered.add(it.match);
      collectRefs(it.ref).forEach((r) => covered.add(r));
      const st = it.match ? status[it.match] : undefined;
      it.baked = st === "done";
      if (it.baked) baked++;
    }
  }

  // ── 3. auto-append any newly-added, still-open launch gaps ──────────────────
  const fresh = [];
  for (const [ref, st] of Object.entries(status)) {
    if (st !== "open") continue;
    if (!LAUNCH_NS_RE.test(ref)) continue;
    if (covered.has(ref)) continue;
    const owner = /^(B|LEAD|Q)/.test(ref) ? "you" : "both";
    fresh.push({
      id: "auto-" + ref, title: title[ref] || ref, owner, ref,
      why: "New in the register — added here automatically. Give it a proper home + guide next time this tool is curated.",
      baked: false,
    });
  }
  if (fresh.length) {
    guides.sections.push({
      num: "＋", title: "Also in the register", meta: "not yet curated",
      note: "Open items in docs/launch-readiness.md that no curated card covers yet — surfaced automatically so nothing is missed. A newly-appended gap lands here first.",
      items: fresh,
    });
  }

  // ── 4. inject into the template ─────────────────────────────────────────────
  const template = readFileSync(TEMPLATE, "utf8");
  const json = JSON.stringify(guides.sections, null, 2);
  if (!template.includes("/*__DATA__*/ []")) {
    throw new Error("template marker `/*__DATA__*/ []` not found — did the template change?");
  }
  const banner = "\n/* GENERATED by tools/launch-readiness/generate.mjs — edit guides.json, not this file. */\n";
  const html = template.replace("/*__DATA__*/ []", json) + "<!--" + banner + "-->";
  writeFileSync(OUT, html);

  const total = guides.sections.reduce((n, s) => n + s.items.length, 0);
  console.log(
    `launch-readiness: wrote ${path.relative(ROOT, OUT)} — ${total} items, ` +
      `${baked} closed in the register${fresh.length ? ", " + fresh.length + " newly-surfaced" : ""}.`
  );
}

build();
